name: Continous integration
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP version
        uses: khs1994-docker/actions-setup-php@master
        with:
          php_version: 7.3.12
          args: |
            mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
                    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini || true
            set -x
            php -v
      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: phpunit
        uses: nathanheffley/laravel-phpunit-action@master

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP version
        uses: khs1994-docker/actions-setup-php@master
        with:
          php_version: 7.3.12
          args: |
            mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
                    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini || true
            set -x
            php -v
      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: phpinsights
        uses: stefanzweifel/phpinsights-action@v1.0.0
        with:
          args: -v --config-path=insights.php --min-quality=100 --min-architecture=100 --min-style=100
